### PR TITLE
GBJ: GP19-38

### PR DESCRIPTION
**Pull request by GBurley-Jones**

### CODE REVIEW

**Comment by dex-mendeley** [comment]
I see you have commited a few files that you probably don't need. You've added .DS_STORE files that are specific to MacOS, so it might make sense to remove those and add the rule to the .gitignore file. 

Adding the .mvn folder and mvnw file usually divides developers, some like to include it, other don't. So it's probably fine to keep :)

**Comment by H-Ford** [comment]
> I see you have commited a few files that you probably don't need. You've added .DS_STORE files that are specific to MacOS, so it might make sense to remove those and add the rule to the .gitignore file.
> 
> Adding the .mvn folder and mvnw file usually divides developers, some like to include it, other don't. So it's probably fine to keep :)

We've got rid of the maven wrapper instead just downloading maven to run the project 😃

**Review by dex-mendeley — APPROVED** [review]
Looks good to me now :)

**Review by H-Ford — APPROVED** [review]
Looks good, make sure you have all downloaded maven (brew install maven)

**Review by singhals-els — APPROVED** [review]

**Pull request merged**
